# Generated by Django 5.1.4 on 2025-01-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saludo', models.CharField(choices=[('Sr.', 'Sr.'), ('Sra.', 'Sra.'), ('Dr.', 'Dr.')], max_length=20)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('invitados', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('zona_horaria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('repeticion', models.CharField(choices=[('Ninguna', 'Ninguna'), ('Diaria', 'Diaria'), ('Semanal', 'Semanal')], default='Ninguna', max_length=50)),
                ('recordatorio', models.BooleanField(default=False)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('coordenadas', models.CharField(max_length=100)),
            ],
        ),
    ]
