# Generated by Django 5.1.4 on 2025-01-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ubicacion_coordenadas_ubicacion_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
