# Generated by Django 5.1.4 on 2025-01-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ubicacion_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
