# Generated by Django 5.1.4 on 2025-01-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_evento_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='numero_telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='saludo',
            field=models.CharField(choices=[('Sr.', 'Sr.'), ('Sra.', 'Sra.'), ('Dr.', 'Dr.')], default='Sr.', max_length=20),
        ),
    ]
